#!/usr/bin/env python3
"""Build the static front-end data file from the SQLite source of truth.

Reads db/resources.db, writes frontend/data.js (an embedded JSON blob the page
reads with plain JS — no server, no internet, double-click to open).

This is the `build_frontend` stage of the quarterly pipeline. Re-run after every
DB rebuild. For the demo it exports the [SAMPLE] seed data.

Usage:  python3 pipeline/build_frontend.py
"""
import json, os, sqlite3, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = os.path.join(ROOT, "db", "resources.db")
OUT = os.path.join(ROOT, "frontend", "data.js")

BUCKET_LABELS = {
    "food": "Food & Groceries", "utility": "Utility Assistance",
    "rent": "Rent Assistance", "pet_food": "Pet Food",
    "gas_transport": "Gas & Transportation", "prescription": "Prescription Help",
    "housing": "Housing", "navigation": "Help Finding Services",
}

def rows(cur, sql, args=()):
    cur.execute(sql, args)
    cols = [c[0] for c in cur.description]
    return [dict(zip(cols, r)) for r in cur.fetchall()]

def build():
    con = sqlite3.connect(DB)
    con.execute("PRAGMA foreign_keys = ON")
    cur = con.cursor()

    zips = rows(cur, "SELECT DISTINCT zip FROM zip_county ORDER BY zip")
    data = {}
    for z in zips:
        zip_code = z["zip"]
        geo = rows(cur, """SELECT county_name, state, zone_id, zone_name
                           FROM v_zip_zone WHERE zip=? AND is_primary=1 LIMIT 1""", (zip_code,))
        geo = geo[0] if geo else {}

        # resources: one row per service-at-location, with org + address + first phone + hours + eligibility
        res = rows(cur, """
            SELECT s.id svc_id, s.name service_name, s.resource_bucket,
                   s.description, s.application_process, s.fees,
                   o.name org_name, o.website,
                   a.address_1, a.city, a.state_province, a.postal_code,
                   s.confidence, s.source_url, s.date_checked
            FROM v_zip_zone zz
            JOIN address a            ON a.zone_id = zz.zone_id AND a.fips = zz.fips
            JOIN location l           ON l.id = a.location_id
            JOIN service_at_location sal ON sal.location_id = l.id
            JOIN service s            ON s.id = sal.service_id AND s.status='active'
            JOIN organization o       ON o.id = s.organization_id
            WHERE zz.zip=? AND zz.is_primary=1
            ORDER BY s.resource_bucket, o.name""", (zip_code,))

        for r in res:
            ph = rows(cur, """SELECT number, type FROM phone
                              WHERE organization_id=(SELECT organization_id FROM service WHERE id=?)
                              ORDER BY id LIMIT 1""", (r["svc_id"],))
            r["phone"] = ph[0]["number"] if ph else None
            sch = rows(cur, "SELECT description FROM schedule WHERE service_id=? LIMIT 1", (r["svc_id"],))
            r["hours"] = sch[0]["description"] if sch else None
            el = rows(cur, "SELECT description FROM eligibility WHERE service_id=? LIMIT 1", (r["svc_id"],))
            r["eligibility"] = el[0]["description"] if el else None
            r["bucket_label"] = BUCKET_LABELS.get(r["resource_bucket"], r["resource_bucket"])
            del r["svc_id"]

        # losses: group benefit_marketing_name -> categories + buckets to point to
        loss_rows = rows(cur, """SELECT carrier_brand, plan_name, plan_year,
                   benefit_marketing_name, ssbci_flag, loss_summary, category, resource_bucket
                   FROM v_losses_by_zip WHERE zip=?""", (zip_code,))
        losses = {}
        for lr in loss_rows:
            key = lr["benefit_marketing_name"]
            if key not in losses:
                losses[key] = {
                    "carrier_brand": lr["carrier_brand"], "plan_name": lr["plan_name"],
                    "plan_year": lr["plan_year"], "ssbci": bool(lr["ssbci_flag"]),
                    "loss_summary": lr["loss_summary"], "categories": [], "buckets": [],
                }
            losses[key]["categories"].append(lr["category"])
            if lr["resource_bucket"] not in losses[key]["buckets"]:
                losses[key]["buckets"].append(lr["resource_bucket"])

        data[zip_code] = {
            "county": geo.get("county_name"), "state": geo.get("state"),
            "zone_id": geo.get("zone_id"), "zone_name": geo.get("zone_name"),
            "resources": res, "losses": list(losses.values()),
        }

    con.close()
    payload = {
        "generated": "STATIC EXPORT",   # date stamped by pipeline run, omitted in demo
        "sample": True,                  # demo flag -> page shows the SAMPLE banner
        "bucket_labels": BUCKET_LABELS,
        "zips": data,
    }
    with open(OUT, "w") as f:
        f.write("// AUTO-GENERATED by pipeline/build_frontend.py — do not edit by hand.\n")
        f.write("window.RESOURCE_DATA = ")
        json.dump(payload, f, indent=1)
        f.write(";\n")
    print(f"wrote {OUT}: {len(data)} ZIPs")

if __name__ == "__main__":
    build()
